name: biu_force
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  fl_chart: ^0.69.0
  file_picker: ^8.1.4
  video_player: ^2.9.2
  audioplayers: ^6.1.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  url_launcher: ^6.3.1
  youtube_player_flutter: ^9.1.1
  webview_flutter: ^4.10.0
  flutter_launcher_icons: ^0.14.1
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  crypto: ^3.0.6
  firebase_storage: ^12.3.6
  smooth_page_indicator: ^1.2.0+3
  http: ^1.2.2
  path: ^1.9.0
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png    
    - assets/default_photo.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_aplikasi.jpg"  

